port: 5002

# number of threads who process network events,
# by default one NetThread corresponds to one WorkerThread.
net_thread_cnt: 4

# The maximum backlog of waiting queue (who holds parsed HTTP packets
# but have not yet been processed by the worker thread).
max_backlog: 4096
